#!/usr/bin/env python3
"""Generate the media query corpus both engines are asked to evaluate.

    python tools/gen_media_corpus.py            # write the corpus
    python tools/gen_media_corpus.py --check    # and fail if it is stale

Writes `tests/media_corpus.txt`, one query per line. `ar_media_corpus` answers
each of them and so does a browser, through `matchMedia`; `tools/compare_media.py`
runs both and reports where they differ.

------------------------------------------------------------------------
What is in it, and what is deliberately not

The queries here are the ones a browser and areole are answering the *same*
question about: the window's width, height, aspect ratio, orientation and
scale, and the syntax that combines them. That is where a bug would be, and
where agreement means something.

Features whose value areole decides for itself are left out, because a
disagreement about them is not a bug in either engine:

  scripting      Chrome runs scripts; areole never will. Permanent, and the
                 whole point of `@media (scripting: none)`.
  display-mode   Chrome is a browser tab; areole is an application.
  hover, pointer, update, prefers-*, forced-colors, color-gamut
                 answered from OS state a headless browser and a library
                 report differently, and wired up at 0.10.2 and 0.16.1.

Those have their own checks in ar_test.c, against the documented default
rather than against a browser.
"""

import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, 'tests', 'media_corpus.txt')

BANNER = [
    '# GENERATED by tools/gen_media_corpus.py. Do not edit.',
    '#',
    '# One media query per line. Both engines answer every one of them at every',
    '# viewport tools/compare_media.py runs; a line starting with # is a comment.',
]

WIDTHS = ['0px', '1px', '320px', '599px', '600px', '601px', '800px', '1200px']
HEIGHTS = ['0px', '300px', '399px', '400px', '401px', '600px', '900px']
RATIOS = ['1/1', '4/3', '16/9', '3/4', '2/1']
RESOLUTIONS = ['1dppx', '1.5dppx', '2dppx', '96dpi', '192dpi', '1x', '2x']


def queries():
    q = []

    # Lengths: legacy both ways, and the three range spellings of each.
    for w in WIDTHS:
        q.append('(min-width: %s)' % w)
        q.append('(max-width: %s)' % w)
        q.append('(width >= %s)' % w)
        q.append('(width <= %s)' % w)
        q.append('(width > %s)' % w)
        q.append('(width < %s)' % w)
        q.append('(%s <= width)' % w)
    for h in HEIGHTS:
        q.append('(min-height: %s)' % h)
        q.append('(max-height: %s)' % h)
        q.append('(height >= %s)' % h)
        q.append('(height < %s)' % h)

    # Two bounds at once, which is the form the range syntax exists for.
    q.append('(400px <= width <= 700px)')
    q.append('(600px <= width <= 1000px)')
    q.append('(0px < width < 10000px)')
    q.append('(300px <= height <= 500px)')

    # The boolean form.
    q.append('(width)')
    q.append('(height)')
    q.append('(resolution)')

    for r in RATIOS:
        q.append('(aspect-ratio: %s)' % r)
        q.append('(min-aspect-ratio: %s)' % r)
        q.append('(max-aspect-ratio: %s)' % r)

    q.append('(orientation: portrait)')
    q.append('(orientation: landscape)')

    for r in RESOLUTIONS:
        q.append('(min-resolution: %s)' % r)
        q.append('(max-resolution: %s)' % r)
        q.append('(resolution: %s)' % r)

    # Types, and the words that go in front of one.
    for t in ['all', 'screen', 'print']:
        q.append(t)
        q.append('not %s' % t)
        q.append('only %s' % t)
        q.append('%s and (min-width: 600px)' % t)

    # Combinators, comma lists and nesting.
    q.append('(min-width: 600px) and (max-width: 900px)')
    q.append('(min-width: 600px) and (min-height: 400px)')
    q.append('(min-width: 9999px) and (min-height: 1px)')
    q.append('(min-width: 600px) or (min-height: 9999px)')
    q.append('(min-width: 9999px) or (min-height: 9999px)')
    q.append('(max-width: 100px), (min-width: 600px)')
    q.append('(max-width: 100px), (max-width: 200px)')
    q.append('(max-width: 100px), (min-width: 600px), (min-height: 1px)')
    q.append('not (min-width: 9999px)')
    q.append('not (min-width: 1px)')
    q.append('((min-width: 600px) and (max-width: 900px))')
    q.append('((min-width: 1px) or (min-width: 9999px)) and (min-height: 1px)')
    q.append('(not (min-width: 9999px)) and (min-width: 1px)')

    # An unknown feature is false in both, and costs only itself in a list.
    q.append('(flibbertigibbet: 3px)')
    q.append('(flibbertigibbet: 3px), (min-width: 1px)')

    #
    # Lengths that are not pixels.
    #
    # This corpus was every bit of it `px` until 0.4.1, which is why it scored
    # 624 of 624 while `@media (min-width: 40em)` matched at no width at all:
    # a length feature took `px` and a bare zero and refused the rest, and a
    # feature that will not parse is false. Agreeing perfectly about the
    # queries it asked said nothing about the ones it did not.
    #
    # `em` and `rem` are the interesting pair. Both are the *initial* font
    # size in a media query -- there is no element to ask, so 40em is 640px in
    # every browser -- and they are also the two a responsive stylesheet is
    # most likely to be written in.
    #
    for u in ['em', 'rem', 'ex', 'ch', 'pt', 'pc', 'in', 'cm', 'mm', 'Q']:
        for n in ['0', '10', '20', '40']:
            q.append('(min-width: %s%s)' % (n, u))
            q.append('(max-width: %s%s)' % (n, u))
        q.append('(width >= 30%s)' % u)

    # The viewport units, which in a query about the viewport are a share of
    # the answer -- so these are arithmetic on the number being asked about
    # rather than breakpoints, and true or false at every size alike.
    for u in ['vw', 'vh', 'vmin', 'vmax', 'vi', 'vb', 'svw', 'svh', 'lvw', 'lvh', 'dvw', 'dvh']:
        q.append('(min-width: 50%s)' % u)
        q.append('(min-height: 50%s)' % u)
        q.append('(max-width: 150%s)' % u)

    # Fractions, which is where hundredths either survive the slot or do not.
    for v in ['1.5em', '2.5rem', '0.5em', '37.5em', '12.5pt', '0.75in']:
        q.append('(min-width: %s)' % v)
        q.append('(max-width: %s)' % v)

    # Case, which CSS does not care about and a hand-written comparison does.
    q.append('(min-width: 40EM)')
    q.append('(min-width: 600PX)')
    q.append('(min-width: 10Rem)')

    # A number that is not a length, and a unit that is not a unit. Both are
    # malformed, so both are false -- which is the difference between a
    # breakpoint that never fires and one that always does.
    q.append('(min-width: 600)')
    q.append('(min-width: 40zz)')
    q.append('(min-width: 40em), (min-width: 1px)')

    return q


def render():
    return '\n'.join(BANNER + queries()) + '\n'


def main():
    text = render()
    if '--check' in sys.argv:
        if not os.path.exists(OUT):
            print('FAIL: %s does not exist' % os.path.relpath(OUT, ROOT))
            return 1
        with io.open(OUT, encoding='utf-8') as f:
            if f.read() != text:
                print('FAIL: %s is stale -- run tools/gen_media_corpus.py'
                      % os.path.relpath(OUT, ROOT))
                return 1
        print('the media corpus is %d queries' % len(queries()))
        return 0
    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('wrote %s, %d queries' % (os.path.relpath(OUT, ROOT), len(queries())))
    return 0


if __name__ == '__main__':
    sys.exit(main())
