#!/usr/bin/env python3
"""Generates docs/PERFORMANCE.md from measured JSON.

    python tools/gen_perf_doc.py

Reads bench/baseline.json and bench/profiles/reference-*.json and writes the
document. Nothing in the output is typed by hand, which is the point: a
published number that can drift from the measured one will drift.

Run it after every baseline refresh. CI checks that the committed document
matches what this produces, so the two cannot disagree.
"""

import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "PERFORMANCE.md")


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def find_reference_profile():
    hits = sorted(glob.glob(os.path.join(ROOT, "bench", "profiles", "reference-*.json")))
    if not hits:
        return None
    return load(hits[0])


def us(v):
    return "%.1f" % v


def rate(v, fmt="%.3f"):
    return (fmt % v) if v > 0 else "-"


def main():
    results = load(os.path.join(ROOT, "bench", "baseline.json"))
    profile = find_reference_profile()
    scenes = results["scenes"]

    out = []
    w = out.append

    w("# Performance")
    w("")
    w("**Generated by `tools/gen_perf_doc.py` from `bench/baseline.json`. Do not edit.**")
    w("")
    w("Every figure here was measured by `ar_bench` on the machine described below, with the")
    w("counters compiled in. Reproduce with:")
    w("")
    w("```sh")
    w("cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build")
    w("./build/ar_bench --all --iters %d --repeat %d --json"
      % (scenes[0]["iters"], scenes[0]["repeats"]))
    w("```")
    w("")

    # ---------------------------------------------------------------- machine
    w("## The machine")
    w("")
    if profile:
        w("```")
        w("%s" % profile.get("name", "(unnamed)"))
        w("clock              %s, %.0f ns resolution"
          % (profile["clock_source"], profile["clock_resolution_ns"]))
        w("scalar latency     %.3g dependent ops/s" % profile["scalar_dependent_ops_per_s"])
        w("scalar throughput  %.3g independent ops/s" % profile["scalar_independent_ops_per_s"])
        w("memory write       %.2f GB/s   scalar 32 bit store loop"
          % profile["mem_write_gbs_scalar"])
        w("memory read        %.2f GB/s" % profile["mem_read_gbs_scalar"])
        w("memory copy        %.2f GB/s   platform memcpy" % profile["mem_copy_gbs_memcpy"])
        w("areole             %s" % results["areole_version"])
        w("```")
    else:
        w("_No reference profile found. Run `ar_hwprobe --json --name ... > "
          "bench/profiles/reference-<machine>.json`._")
    w("")
    w("A rate without its machine is not a rate. Everything below is this machine and")
    w("says nothing directly about any other; `ar_require` is what converts between them.")
    w("")

    # ------------------------------------------------------------- stability
    spreads = sorted(s["stability_pct"] for s in scenes)
    median = spreads[len(spreads) // 2]
    worst = spreads[-1]
    tight = sum(1 for v in spreads if v <= 4.0)

    w("## How much to trust these numbers")
    w("")
    w("| | |")
    w("| --- | --- |")
    w("| median spread between epochs | **%.1f%%** |" % median)
    w("| worst | %.1f%% |" % worst)
    w("| scenes within 4%% | %d of %d |" % (tight, len(scenes)))
    w("")
    w("An epoch is a complete pass over every scene, so a scene is measured again only")
    w("after the whole rest of the list has run. That approximates a second invocation")
    w("of the tool, which is the variance a regression gate actually has to tolerate.")
    w("")
    if median > 8.0:
        w("**This machine is too noisy for a tight gate.** The thresholds derived from these")
        w("spreads will only catch gross changes. A quiet unshared machine with boost")
        w("disabled is what a real gate needs, and nothing in the tool substitutes for one.")
    else:
        w("This machine can support a gate at roughly %.0f%% on most scenes." % (median * 2))
    w("")

    # ---------------------------------------------------------------- scenes
    by_group = {}
    for s in scenes:
        by_group.setdefault(s["group"], []).append(s)

    w("## Scenes")
    w("")
    for group in ["primitive", "text", "layout", "style", "realistic", "pathological"]:
        if group not in by_group:
            continue
        w("### %s" % group)
        w("")
        w("| scene | p50 | p95 | p99 | spread | ns/px | ns/glyph | ns/node |")
        w("| --- | --: | --: | --: | --: | --: | --: | --: |")
        for s in by_group[group]:
            w("| `%s` | %s µs | %s µs | %s µs | %.1f%% | %s | %s | %s |"
              % (s["name"], us(s["p50_us"]), us(s["p95_us"]), us(s["p99_us"]),
                 s["stability_pct"], rate(s["ns_per_px"]), rate(s["ns_per_glyph"], "%.1f"),
                 rate(s["ns_per_node"], "%.1f")))
        w("")
        for s in by_group[group]:
            w("- `%s` — %s" % (s["name"], s["stresses"]))
        w("")

    # --------------------------------------------------------------- findings
    def get(name):
        for s in scenes:
            if s["name"] == name:
                return s
        return None

    w("## What the numbers say")
    w("")
    cached, uncached = get("clear_cached"), get("clear_uncached")
    if cached and uncached and cached["ns_per_px"] > 0:
        w("**The rasterizer is bandwidth bound, not compute bound.** `clear_cached` and")
        w("`clear_uncached` run identical code. The first fills at %.3f ns per pixel, the"
          % cached["ns_per_px"])
        w("second at %.3f, a factor of %.1f, purely because one surface fits in cache and"
          % (uncached["ns_per_px"], uncached["ns_per_px"] / cached["ns_per_px"]))
        w("the other does not. The target hardware can never satisfy the first condition,")
        w("so the uncached figure is the one that transfers.")
        w("")

    op, bl = get("fill_opaque"), get("fill_blend")
    if op and bl and op["ns_per_px"] > 0:
        w("**Blending costs %.1f times opaque filling** — %.3f against %.3f ns per pixel. It"
          % (bl["ns_per_px"] / op["ns_per_px"], bl["ns_per_px"], op["ns_per_px"]))
        w("reads, blends and writes where opaque only writes, and does four multiplies per")
        w("pixel. That ratio is the measured case for SIMD in 0.15.0.")
        w("")

    t1, t2 = get("latin_paragraph"), get("latin_paragraph_2x")
    if t1 and t2 and t1["ns_per_glyph"] > 0:
        w("**The glyph blitter costs per bit tested, not per pixel written.** At scale 2 it")
        w("draws four times the pixels for %.2f times the money — %.0f against %.0f ns per"
          % (t2["ns_per_glyph"] / t1["ns_per_glyph"], t2["ns_per_glyph"], t1["ns_per_glyph"]))
        w("glyph. Every ink pixel goes through a function call performing two rectangle")
        w("intersections. 0.2.0 replaces the whole path and inherits a tenfold improvement")
        w("as its acceptance criterion.")
        w("")

    r10, r100, r250 = get("rules_10"), get("rules_100"), get("rules_250")
    if r10 and r100 and r250:
        w("**Style resolution is linear in rule count.** %s, %s and %s µs for 13, 103 and 253"
          % (us(r10["p50_us"]), us(r100["p50_us"]), us(r250["p50_us"])))
        w("rules over the same 500 boxes: resolution scans every rule for every box. A")
        w("browser user-agent stylesheet alone is around 400 rules, which is why 0.4.0")
        w("builds a style cache and why the rule table has to stop being a fixed 256.")
        w("")

    allocs = sum(s["allocations_after_init"] for s in scenes)
    w("**Allocations after init: %d**, across all %d scenes. Checked by watching the"
      % (allocs, len(scenes)))
    w("persistent half of the arena rather than by assertion. This is the property that")
    w("makes p99 equal p50.")
    w("")

    w("## What is not here yet")
    w("")
    w("- Numbers from real Pentium II hardware, or from 86Box. Every figure for that tier")
    w("  in `docs/roadmap/hardware-tiers.md` is derived and labelled as such.")
    w("- A comparison against Clay, Nuklear, microui, LVGL, GDI and Direct2D.")
    w("- Cold start and binary size as gated numbers rather than one-off measurements.")

    text = "\n".join(out) + "\n"

    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            print("PERFORMANCE.md does not exist; run without --check")
            return 1
        with open(OUT, encoding="utf-8") as f:
            if f.read() != text:
                print("PERFORMANCE.md is out of date with bench/baseline.json.")
                print("Run: python tools/gen_perf_doc.py")
                return 1
        print("PERFORMANCE.md matches the measured baseline")
        return 0

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s from %d scenes" % (OUT, len(scenes)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
