#!/usr/bin/env python3
"""Generates docs/COMPARISON.md from bench/comparison.json.

    python tools/gen_compare_doc.py
    python tools/gen_compare_doc.py --check

Who wins, by how much, and how much of that survives the noise it was measured
in. Nothing in the output is typed by hand, for the same reason nothing in
PERFORMANCE.md is: a published number that can drift from the measured one
will drift, and this one is a comparison against other people's software, so
being wrong about it is worse than being silent.

The harness records a `fair` flag and a caveat for every case, and this
document prints both next to every ratio rather than at the bottom. A
comparison that hides its caveats is an advertisement.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "COMPARISON.md")
COMPARISON = os.path.join(ROOT, "bench", "comparison.json")
PROFILE_GLOB = os.path.join(ROOT, "bench", "profiles")


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def strength(case):
    """How much of a ratio survives the noise that produced it.

    The effect is how far the ratio is from parity; the noise is how much the
    two engines each moved between epochs. A ratio smaller than the noise that
    produced it is not a finding, and saying so in the table is cheaper than
    having somebody quote it back later. Same rule gen_perf_doc.py applies to
    its own numbers.
    """
    ratio = case["ratio"]
    effect = abs(ratio - 1.0) * 100.0
    noise = case.get("areole_spread_pct", 0.0) + case.get("rival_spread_pct", 0.0)
    if effect > 2.0 * noise:
        return "solid"
    if effect > noise:
        return "marginal"
    return "noise"


def verdict(ratio, how_solid):
    """Who wins this case, in words rather than in a number to be misread."""
    if how_solid == "noise":
        return "a tie"
    if ratio >= 1.0:
        return "**areole** by %.2fx" % ratio
    return "the rival by %.2fx" % (1.0 / ratio) if ratio > 0 else "the rival"


def find_profile():
    if not os.path.isdir(PROFILE_GLOB):
        return None
    hits = sorted(
        os.path.join(PROFILE_GLOB, f)
        for f in os.listdir(PROFILE_GLOB)
        if f.startswith("reference-") and f.endswith(".json")
    )
    return load(hits[0]) if hits else None


def main():
    data = load(COMPARISON)
    profile = find_profile()

    out = []
    w = out.append

    w("# areole against other engines")
    w("")
    w("**Generated by `tools/gen_compare_doc.py` from `bench/comparison.json`. Do not edit.**")
    w("")
    w("Reproduce with:")
    w("")
    w("```sh")
    w("cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build")
    w("./build/ar_compare --all --iters %d --repeat %d --json > bench/comparison.json"
      % (data.get("iters", 0), data.get("epochs", 0)))
    w("python tools/gen_compare_doc.py")
    w("```")
    w("")

    # ------------------------------------------------------------- the machine
    w("## The machine")
    w("")
    w("```")
    if profile:
        w("%s" % profile.get("name", "(unnamed)"))
    w("areole             %s" % data.get("areole_version", "(unstamped)"))
    w("clock              %s" % data.get("clock", "(unstated)"))
    w("iterations         %d timed frames per epoch, %d epochs"
      % (data.get("iters", 0), data.get("epochs", 0)))
    w("```")
    w("")
    w("A rate without its machine is not a rate, and a *comparison* without its machine is not")
    w("even that: both engines were built by the same compiler, at the same flags, and run back")
    w("to back on the same idle machine. Any of those three changing invalidates the row.")
    w("")

    # ---------------------------------------------------------------- the rules
    w("## How to read this")
    w("")
    w("| | |")
    w("| --- | --- |")
    w("| **areole** | this engine wins the case |")
    w("| **the rival** | the other one does |")
    w("| **a tie** | the difference is smaller than the noise it was measured in |")
    w("| `fair` | the two engines were asked to do the same work |")
    w("| `not fair` | they were not, and the caveat says how. **Read it before quoting the number.** |")
    w("")
    w("`solid` means the effect is more than twice the combined spread of the two engines;")
    w("`marginal` means it is larger than the spread but not twice it; `noise` means it is not.")
    w("Only `solid` rows are worth an argument.")
    w("")

    # ------------------------------------------------------------- the results
    total_fair_wins = 0
    total_fair = 0

    for engine in data["engines"]:
        name = engine["engine"]
        w("---")
        w("")
        w("## vs %s" % name)
        w("")
        w("| case | what it measures | areole | %s | who wins | confidence | fair |"
          % name)
        w("| --- | --- | --: | --: | --- | :-: | :-: |")
        for case in engine["cases"]:
            how = strength(case)
            fair = case.get("fair", False)
            if fair:
                total_fair += 1
                if case["ratio"] >= 1.0 and how != "noise":
                    total_fair_wins += 1
            w("| `%s` | %s | %.1f µs | %.1f µs | %s | %s | %s |"
              % (case["name"], case.get("what", ""), case["areole_us"], case["rival_us"],
                 verdict(case["ratio"], how), how, "yes" if fair else "**no**"))
        w("")

        # Every caveat, in full, under the table it belongs to.
        caveated = [c for c in engine["cases"] if c.get("caveat")]
        if caveated:
            w("### The caveats")
            w("")
            for case in caveated:
                w("**`%s`** — %s" % (case["name"], case["caveat"]))
                if case.get("extra_label") and case.get("extra_ratio"):
                    w("")
                    w("> The fair comparison for this case is **%s** at %.1f µs, which is %s."
                      % (case["extra_label"], case["extra_us"],
                         verdict(case["extra_ratio"], "solid")))
                w("")

    # ------------------------------------------------------------- the summary
    w("---")
    w("")
    w("## The short version")
    w("")
    w("Of the %d cases where both engines were asked to do the same work, areole wins **%d**."
      % (total_fair, total_fair_wins))
    w("")
    w("The unfair cases are not padding and are not hidden: they are the ones where areole is")
    w("doing strictly more work than the rival, and where the rival is doing something areole")
    w("has not implemented. Both directions are in the tables above with the reason attached.")
    w("")
    w("## What is not compared")
    w("")
    w("- **Nuklear, LVGL and Direct2D are not vendored.** Three engines are here; those three")
    w("  are not, and their absence is a gap rather than a result.")
    w("- **Nothing is compared for memory, binary size or startup.** This harness measures")
    w("  frame time only.")
    w("- **No engine here renders HTML.** areole does not either, until 0.9.0. The layout cases")
    w("  compare a box tree built through each engine's own API.")
    w("- **A tie against a system toolkit is not a moral victory and not a defeat.** GDI has")
    w("  been optimised for thirty years by people with the source of the kernel; matching it")
    w("  at anything is the interesting result, in either direction.")

    text = "\n".join(out) + "\n"

    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            print("COMPARISON.md does not exist; run without --check")
            return 1
        with open(OUT, encoding="utf-8") as f:
            if f.read() != text:
                print("COMPARISON.md is out of date with bench/comparison.json.")
                print("Run: python tools/gen_compare_doc.py")
                return 1
        print("COMPARISON.md matches the measured comparison")
        return 0

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s from %d engines" % (OUT, len(data["engines"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
