#!/usr/bin/env python3
"""Generates docs/PERFORMANCE.md from measured JSON.

    python tools/gen_perf_doc.py

Reads bench/baseline.json and bench/profiles/reference-*.json and writes the
document. Nothing in the output is typed by hand, which is the point: a
published number that can drift from the measured one will drift.

Run it after every baseline refresh. CI checks that the committed document
matches what this produces, so the two cannot disagree.
"""

import glob
import json
import os
import re
import sys
import textwrap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "PERFORMANCE.md")


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def registered_scenes():
    """Every scene name in bench/scenes/, read from the source rather than run.

    The CI job that calls --check does not build anything, so this cannot ask
    ar_bench --list. It reads the initialisers instead, which is enough: a
    scene is a `bench_scene` whose first member is its name.

    sc_outline.c is excluded on purpose. Those four scenes only register when
    --font names a face, so a baseline taken without one is complete without
    them and demanding them would make this gate unpassable.
    """
    names = set()
    pattern = re.compile(r"bench_scene\s+(?:SC_[A-Z0-9_]+)\s*=\s*\{")
    for path in sorted(glob.glob(os.path.join(ROOT, "bench", "scenes", "*.c"))):
        if os.path.basename(path) == "sc_outline.c":
            continue
        with open(path, encoding="utf-8", errors="replace") as f:
            src = f.read()
        for m in pattern.finditer(src):
            first = re.search(r'"([a-z0-9_]+)"', src[m.end():m.end() + 400])
            if first:
                names.add(first.group(1))
    return names


def header_version():
    """AR_VERSION_STRING, straight out of include/areole.h."""
    path = os.path.join(ROOT, "include", "areole.h")
    with open(path, encoding="utf-8") as f:
        m = re.search(r'#\s*define\s+AR_VERSION_STRING\s+"([^"]+)"', f.read())
    return m.group(1) if m else None


def check_baseline_is_complete(baseline):
    """The two ways a baseline lies without being wrong.

    Both of these were true for four releases and no gate noticed, because the
    only gate here compared the document against the baseline and never asked
    whether the baseline described the engine.

    A scene missing from the baseline is published nowhere and cannot regress:
    bench/baseline.json held 33 of 47, so tables, grid, flex, sticky, the top
    layer and anchor positioning were measured by ar_bench on every run and
    absent from docs/PERFORMANCE.md entirely.

    A baseline stamped with a stale version mislabels every number in it.
    AR_VERSION_STRING sat at 0.6.1-dev through five releases and the machine
    block of the generated document repeated it each time.
    """
    problems = []

    measured = set(s["name"] for s in baseline["scenes"])
    missing = sorted(registered_scenes() - measured)
    if missing:
        problems.append(
            "bench/baseline.json is missing %d registered scene(s): %s"
            % (len(missing), ", ".join(missing))
        )

    want = header_version()
    got = baseline.get("areole_version")
    if want and got and want != got:
        problems.append(
            "bench/baseline.json was measured by areole %s, but include/areole.h says %s"
            % (got, want)
        )

    return problems


def find_reference_profile():
    hits = sorted(glob.glob(os.path.join(ROOT, "bench", "profiles", "reference-*.json")))
    if not hits:
        return None
    return load(hits[0])


def find_outline():
    path = os.path.join(ROOT, "bench", "outline.json")
    return load(path) if os.path.exists(path) else None


def find_comparison():
    path = os.path.join(ROOT, "bench", "comparison.json")
    return load(path) if os.path.exists(path) else None


def read_strength(c):
    """How much of a ratio survives the noise it was measured in.

    The effect is how far the ratio is from parity; the noise is how much the
    two engines each moved between epochs. A ratio smaller than the noise that
    produced it is not a finding, and saying so in the table is cheaper than
    having someone quote it back later.
    """
    effect = abs(c["ratio"] - 1.0) * 100.0
    noise = c["areole_spread_pct"] + c["rival_spread_pct"]
    if effect > 2.0 * noise:
        return "solid"
    if effect > noise:
        return "marginal"
    return "noise"


def us(v):
    return "%.1f" % v


def rate(v, fmt="%.3f"):
    return (fmt % v) if v > 0 else "-"


def main():
    results = load(os.path.join(ROOT, "bench", "baseline.json"))
    profile = find_reference_profile()
    scenes = results["scenes"]

    out = []
    w = out.append

    w("# Performance")
    w("")
    w("**Generated by `tools/gen_perf_doc.py` from `bench/baseline.json`. Do not edit.**")
    w("")
    w("Every figure here was measured by `ar_bench` on the machine described below, with the")
    w("counters compiled in. Reproduce with:")
    w("")
    w("```sh")
    w("cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build")
    w("./build/ar_bench --all --iters %d --repeat %d --json"
      % (scenes[0]["iters"], scenes[0]["repeats"]))
    w("```")
    w("")

    # ---------------------------------------------------------------- machine
    w("## The machine")
    w("")
    if profile:
        w("```")
        w("%s" % profile.get("name", "(unnamed)"))
        w("clock              %s, %.0f ns resolution"
          % (profile["clock_source"], profile["clock_resolution_ns"]))
        w("scalar latency     %.3g dependent ops/s" % profile["scalar_dependent_ops_per_s"])
        w("scalar throughput  %.3g independent ops/s" % profile["scalar_independent_ops_per_s"])
        w("memory write       %.2f GB/s   scalar 32 bit store loop"
          % profile["mem_write_gbs_scalar"])
        w("memory read        %.2f GB/s" % profile["mem_read_gbs_scalar"])
        w("memory copy        %.2f GB/s   platform memcpy" % profile["mem_copy_gbs_memcpy"])
        w("areole             %s" % results["areole_version"])
        w("```")
    else:
        w("_No reference profile found. Run `ar_hwprobe --json --name ... > "
          "bench/profiles/reference-<machine>.json`._")
    w("")
    w("A rate without its machine is not a rate. Everything below is this machine and")
    w("says nothing directly about any other; `ar_require` is what converts between them.")
    w("")

    # ------------------------------------------------------------- stability
    spreads = sorted(s["stability_pct"] for s in scenes)
    median = spreads[len(spreads) // 2]
    worst = spreads[-1]
    tight = sum(1 for v in spreads if v <= 4.0)

    w("## How much to trust these numbers")
    w("")
    w("| | |")
    w("| --- | --- |")
    w("| median spread between epochs | **%.1f%%** |" % median)
    w("| worst | %.1f%% |" % worst)
    w("| scenes within 4%% | %d of %d |" % (tight, len(scenes)))
    w("")
    w("An epoch is a complete pass over every scene, so a scene is measured again only")
    w("after the whole rest of the list has run. That approximates a second invocation")
    w("of the tool, which is the variance a regression gate actually has to tolerate.")
    w("")
    if median > 8.0:
        w("**This machine is too noisy for a tight gate.** The thresholds derived from these")
        w("spreads will only catch gross changes. A quiet unshared machine with boost")
        w("disabled is what a real gate needs, and nothing in the tool substitutes for one.")
    else:
        w("This machine can support a gate at roughly %.0f%% on most scenes." % (median * 2))
    w("")

    # ---------------------------------------------------------------- scenes
    by_group = {}
    for s in scenes:
        by_group.setdefault(s["group"], []).append(s)

    w("## Scenes")
    w("")
    for group in ["primitive", "text", "layout", "style", "realistic", "pathological"]:
        if group not in by_group:
            continue
        w("### %s" % group)
        w("")
        # fill_px and glyph_px are what a damage or region-move change actually
        # moves; p50 can sit still while painting collapses, which is exactly
        # what the region move did. Printed for the groups where drawing is
        # driven by a tree, since for a primitive scene ns/px already says it.
        painted = group in ("layout", "realistic")
        if painted:
            w("| scene | p50 | p95 | p99 | spread | fill px | glyph px | ns/px | ns/glyph | ns/node |")
            w("| --- | --: | --: | --: | --: | --: | --: | --: | --: | --: |")
        else:
            w("| scene | p50 | p95 | p99 | spread | ns/px | ns/glyph | ns/node |")
            w("| --- | --: | --: | --: | --: | --: | --: | --: |")
        for s in by_group[group]:
            tail = ("%.1f%% | %s | %s | %s |"
                    % (s["stability_pct"], rate(s["ns_per_px"]),
                       rate(s["ns_per_glyph"], "%.1f"), rate(s["ns_per_node"], "%.1f")))
            if painted:
                tail = ("%.1f%% | %d | %d | %s | %s | %s |"
                        % (s["stability_pct"], s["fill_px"], s["glyph_px"],
                           rate(s["ns_per_px"]), rate(s["ns_per_glyph"], "%.1f"),
                           rate(s["ns_per_node"], "%.1f")))
            w("| `%s` | %s µs | %s µs | %s µs | %s"
              % (s["name"], us(s["p50_us"]), us(s["p95_us"]), us(s["p99_us"]), tail))
        w("")
        for s in by_group[group]:
            w("- `%s` — %s" % (s["name"], s["stresses"]))
        w("")

    # --------------------------------------------------------------- findings
    def get(name):
        for s in scenes:
            if s["name"] == name:
                return s
        return None

    w("## What the numbers say")
    w("")
    cached, uncached = get("clear_cached"), get("clear_uncached")
    if cached and uncached and cached["ns_per_px"] > 0:
        w("**The rasterizer is bandwidth bound, not compute bound.** `clear_cached` and")
        w("`clear_uncached` run identical code. The first fills at %.3f ns per pixel, the"
          % cached["ns_per_px"])
        w("second at %.3f, a factor of %.1f, purely because one surface fits in cache and"
          % (uncached["ns_per_px"], uncached["ns_per_px"] / cached["ns_per_px"]))
        w("the other does not. The target hardware can never satisfy the first condition,")
        w("so the uncached figure is the one that transfers.")
        w("")

    op, bl = get("fill_opaque"), get("fill_blend")
    if op and bl and op["ns_per_px"] > 0:
        w("**Blending costs %.1f times opaque filling** — %.3f against %.3f ns per pixel. It"
          % (bl["ns_per_px"] / op["ns_per_px"], bl["ns_per_px"], op["ns_per_px"]))
        w("reads, blends and writes where opaque only writes, and does four multiplies per")
        w("pixel. That ratio is the measured case for SIMD in 0.15.0.")
        w("")

    t1, t2 = get("latin_paragraph"), get("latin_paragraph_2x")
    if t1 and t2 and t1["ns_per_glyph"] > 0:
        scale_ratio = t2["ns_per_glyph"] / t1["ns_per_glyph"]
        # The scene exists to measure one thing: scale 2 draws four times the
        # pixels, so a blitter paying per pixel written costs 4x and one paying
        # per bit tested costs 1x. The original blitter measured 1.04x. Saying
        # which of those the current number is nearer is the whole finding, and
        # hardcoding either verdict is how this passage went stale before.
        if scale_ratio < 2.0:
            verdict = ("**The bitmap glyph blitter costs per bit tested, not per pixel written.**"
                       " At scale 2 it")
        elif scale_ratio < 3.5:
            verdict = ("**The bitmap glyph blitter pays partly per pixel and partly per bit.**"
                       " At scale 2 it")
        else:
            verdict = ("**The bitmap glyph blitter costs per pixel written, as it should.**"
                       " At scale 2 it")
        w(verdict)
        w("draws four times the pixels for %.2f times the money — %.0f against %.0f ns per"
          % (scale_ratio, t2["ns_per_glyph"], t1["ns_per_glyph"]))
        w("glyph. Four is what a blitter paying per pixel written would cost and one is what")
        w("the original per-set-pixel path did cost, so the distance between them is the")
        w("finding. These two scenes measure the built-in 8x8 face, which is what")
        w("`ar_draw_text` uses when no font is loaded; 0.2.0's outline path is measured")
        w("separately under **Outline text** below.")
        w("")

    r10, r100, r250 = get("rules_10"), get("rules_100"), get("rules_250")
    if r10 and r100 and r250:
        # This passage asserted "linear in rule count" for long enough to
        # outlive the style cache that flattened it, while printing the three
        # numbers that refuted it. Decide from the data instead: the curve is
        # flat when the 253-rule sheet costs no more than the 13-rule one by
        # more than the noise the two were measured in.
        noise = r10["stability_pct"] + r250["stability_pct"]
        growth = (r250["p50_us"] / r10["p50_us"] - 1.0) * 100.0 if r10["p50_us"] else 0.0
        if growth > noise:
            w("**Style resolution still grows with rule count.** %s, %s and %s µs for 13, 103"
              % (us(r10["p50_us"]), us(r100["p50_us"]), us(r250["p50_us"])))
            w("and 253 rules over the same 500 boxes — %.0f%% for 19 times the rules, against"
              % growth)
            w("%.0f%% of measurement noise. The resolved-style cache is not covering this"
              % noise)
            w("sheet; the hit rate in the scene table says whether it is missing or thrashing.")
        else:
            w("**Style resolution no longer grows with rule count.** %s, %s and %s µs for 13,"
              % (us(r10["p50_us"]), us(r100["p50_us"]), us(r250["p50_us"])))
            # abs(): a curve that came out slightly *cheaper* at 253 rules than at
            # 13 is still flat, and "-0% apart" reads like a typo in a published
            # document rather than the noise it is.
            w("103 and 253 rules over the same 500 boxes: %.0f%% apart across 19 times the"
              % abs(growth))
            w("rules, inside the %.0f%% these were measured in. The resolved-style cache did"
              % noise)
            w("that — matching is keyed on `(tag, class, id, state)` and a repeat is a lookup")
            w("rather than a scan.")
        w("")
        # What the cache did not fix, which is the number that matters next.
        per_box = [(s["style_us"] * 1000.0 / s["nodes"], s)
                   for s in (r10, r250, get("identical_siblings")) if s and s["nodes"]]
        if len(per_box) == 3:
            w("**What it did not fix is the per-box cost.** Style is %.0f ns a box on a %s"
              % (per_box[0][0], "13 rule sheet"))
            w("and %.0f ns a box on a 253 rule sheet, and %.0f ns a box across the thousand"
              % (per_box[1][0], per_box[2][0]))
            w("identically-classed boxes of `identical_siblings` — the case where every box")
            w("after the first is a cache hit. A hit still copies the whole resolved `ar_style`")
            w("into the box, so rule count stopped mattering and box count did not. That is")
            w("what style sharing in 0.15.0 is for.")
            w("")
        w("A browser user-agent stylesheet alone is around 400 rules, and `AR_MAX_RULES` is")
        w("still a fixed 256, so a sheet that size cannot be loaded at all yet.")
        w("")

    # A scroll is the case where "presented" and "painted" come apart, and the
    # two columns disagreeing is the region move working rather than a fault.
    # Printed from whichever scene shows the widest gap so this survives the
    # scene list being renamed or added to.
    moved = [s for s in scenes
             if s["dirty_ratio"] > 0.5 and s["nodes"] > 0 and s["fill_px"] > 0]
    if moved:
        sc = max(moved, key=lambda s: s["dirty_ratio"] / max(s["fill_px"], 1))
        w("**Presented and painted are different numbers, and scrolling is where they")
        w("part.** `%s` reports a dirty ratio of %.3f — it presents essentially its"
          % (sc["name"], sc["dirty_ratio"]))
        w("whole surface every frame — while painting only %d pixels and rasterising %d"
          % (sc["fill_px"], sc["glyph_px"]))
        w("glyphs to do it. Both are true: a scroll really does change every pixel of the")
        w("container on screen, because they *moved*, so every one of them has to be")
        w("presented. The region move is what moves them without painting them, and")
        w("`fill_px` is the column that shows it. An acceptance criterion written in terms")
        w("of pixels \"touched\" is asking about `fill_px`; `dirty_ratio` cannot go below")
        w("the container for a scroll and never will.")
        w("")
        w("It bought the painting and not the frame. Style is %d µs and layout %d µs against"
          % (sc["style_us"], sc["layout_us"]))
        w("a raster of %d, so the frame is owned by the two passes that still run over every"
          % sc["raster_us"])
        w("box in the tree whatever the surface does — %d of them here, %.0f%% of which are"
          % (sc["nodes"], 100.0 * sc["clipped_out"] / sc["nodes"]))
        w("clipped out before a pixel is drawn. The next scroll win is incremental layout,")
        w("not painting.")
        w("")

    allocs = sum(s["allocations_after_init"] for s in scenes)
    w("**Allocations after init: %d**, across all %d scenes. Checked by watching the"
      % (allocs, len(scenes)))
    w("persistent half of the arena rather than by assertion. This is the property that")
    w("makes p99 equal p50.")
    w("")

    outline = find_outline()
    if outline:
        by = {}
        for sc in outline["scenes"]:
            by[sc["name"]] = sc

        w("## Outline text")
        w("")
        w("Measured with `%s`. These scenes need a real font file, so they exist"
          % os.path.basename(outline.get("font", "a TrueType face")))
        w("only when `ar_bench --font` names one, and the face is named here because \"text")
        w("costs 220 ns a glyph\" without saying whose text at what size is an anecdote")
        w("rather than a measurement.")
        w("")
        w("```sh")
        w("./build/ar_bench --group outline --font /path/to/face.ttf --iters 600 --repeat 3")
        w("```")
        w("")
        w("| scene | p50 | ns/glyph | spread | what it says |")
        w("| --- | --: | --: | --: | --- |")
        for name, says in (
            ("outline_aa", "antialiased, glyphs cached: the ordinary case"),
            ("outline_aliased", "the same with antialiasing off"),
            ("outline_sizes", "16 sizes at once, up to 40 px, so the glyphs are larger"),
            ("outline_cold", "cache dropped every frame: rasterizing, not blitting"),
        ):
            sc = by.get(name)
            if not sc:
                continue
            w("| `%s` | %s us | %.0f | %.0f%% | %s |"
              % (name, us(sc["p50_us"]), sc["ns_per_glyph"], sc["stability_pct"], says))
        w("")

        aa = by.get("outline_aa")
        al = by.get("outline_aliased")
        cold = by.get("outline_cold")
        worst = max(sc["stability_pct"] for sc in outline["scenes"])

        if worst > 15.0:
            w("**This run was too noisy to quote ratios from.** The worst spread above is")
            w("%.0f%%, so treat the two figures below as indicative and re-run on a quiet"
              % worst)
            w("machine before citing them.")
            w("")

        w("Read the ratios rather than the absolute times. Across three runs of this set the")
        w("per-glyph figures moved by 1.7x with nothing changed but machine load, while the")
        w("two ratios below stayed within 0.05 of each other: a ratio cancels whatever was")
        w("varying.")
        w("")

        if aa and al and al["ns_per_glyph"] > 0:
            w("**Antialiasing off is %.2fx faster.** A blend reads and writes where an opaque"
              % (aa["ns_per_glyph"] / al["ns_per_glyph"]))
            w("store only writes, and on a machine whose whole problem is memory bandwidth that")
            w("is the entire difference. `ar_font_antialias` exposes it as a setting.")
            w("")
        if aa and cold and aa["ns_per_glyph"] > 0:
            w("**Rasterizing costs %.1fx blitting a cached glyph.** That is why the cache is not"
              % (cold["ns_per_glyph"] / aa["ns_per_glyph"]))
            w("an optimisation but the thing that makes outlines usable at all -- measured,")
            w("rather than asserted in a design document.")
            w("")

    comparison = find_comparison()
    if comparison:
        w("## Against the alternatives")
        w("")
        w("Measured by `ar_compare`, %d frames per engine per epoch, %d epochs, alternating one"
          % (comparison["iters"], comparison["epochs"]))
        w("frame each so neither engine sits on a warmer machine. Reproduce with:")
        w("")
        w("```sh")
        w("./build/ar_compare --all --iters %d --repeat %d"
          % (comparison["iters"], comparison["epochs"]))
        w("```")
        w("")
        w("A ratio above 1.00 means areole is faster. Cases that cannot be made fair carry a")
        w("note, and the note is the point: an unfair comparison presented without one is worth")
        w("less than no comparison at all.")
        w("")
        w("Case names are the scene names `ar_bench` uses, so a row here can be read against the")
        w("same row in the scene tables above. `dashboard` is absent on purpose: comparing a whole")
        w("realistic interface would mean replaying areole's drawing through a rival, and areole")
        w("has no public command list to replay. Adding library API to serve a benchmark is a")
        w("worse trade than leaving the row out and saying why.")
        w("")
        w("`spread` is how far each engine's per-epoch median moved, areole first. `read` says")
        w("whether the ratio survives that noise: **solid** when the effect is more than twice")
        w("the combined spread, **marginal** when it merely exceeds it, **noise** when it does")
        w("not. A `noise` row is a tie, whatever its ratio column says, and rows are published")
        w("that way rather than dropped.")
        w("")
        for eng in comparison["engines"]:
            w("### %s" % eng["engine"])
            w("")
            has_extra = any("extra_us" in c for c in eng["cases"])
            if has_extra:
                w("| case | areole | %s | ratio | areole layout | ratio | spread | read |"
                  % eng["engine"])
                w("| --- | --: | --: | --: | --: | --: | --: | --- |")
            else:
                w("| case | areole | %s | ratio | spread | read |" % eng["engine"])
                w("| --- | --: | --: | --: | --: | --- |")
            for c in eng["cases"]:
                mark = " *" if c.get("caveat") else ""
                row = "| `%s`%s | %s us | %s us | **%.2fx** |" % (
                    c["name"], mark, us(c["areole_us"]), us(c["rival_us"]), c["ratio"])
                if has_extra:
                    if "extra_us" in c:
                        row += " %s us | **%.2fx** |" % (us(c["extra_us"]), c["extra_ratio"])
                    else:
                        row += " - | - |"
                row += " %.0f/%.0f%% | %s |" % (c["areole_spread_pct"],
                                                c["rival_spread_pct"],
                                                read_strength(c))
                w(row)
            w("")
            # The caveat text is carried in the JSON rather than retyped here, so a
            # number and the reason it is not what it looks like cannot drift apart.
            seen = []
            for c in eng["cases"]:
                cav = c.get("caveat")
                if cav and cav not in seen:
                    seen.append(cav)
                    names = [x["name"] for x in eng["cases"] if x.get("caveat") == cav]
                    lead = "\\* `%s`: " % "`, `".join(names)
                    for line in textwrap.wrap(lead + cav, 95,
                                              subsequent_indent="  "):
                        w(line)
                    w("")
            if not seen:
                w("")

    w("## What is not here yet")
    w("")
    w("- Numbers from real Pentium II hardware, or from 86Box. Every figure for that tier")
    w("  in `docs/roadmap/hardware-tiers.md` is derived and labelled as such.")
    w("- A comparison against Nuklear, LVGL and Direct2D. GDI, Clay and microui are done.")
    w("- Outline text on the Pentium II tier. The figures above are reference-machine only.")
    w("- Cold start and binary size as gated numbers rather than one-off measurements.")

    text = "\n".join(out) + "\n"

    # Whether the baseline is complete is asked on both paths, not just under
    # --check. Regenerating from a baseline that is missing scenes republishes
    # the gap, and that is exactly how it lasted four releases.
    problems = check_baseline_is_complete(results)
    for p in problems:
        print("FAIL: %s" % p)

    if "--check" in sys.argv:
        if problems:
            print("Run: ./build/ar_bench --all --iters 150 --repeat 3 --json > bench/baseline.json")
            return 1
        if not os.path.exists(OUT):
            print("PERFORMANCE.md does not exist; run without --check")
            return 1
        with open(OUT, encoding="utf-8") as f:
            if f.read() != text:
                print("PERFORMANCE.md is out of date with bench/baseline.json.")
                print("Run: python tools/gen_perf_doc.py")
                return 1
        print("PERFORMANCE.md matches the measured baseline, %d scenes, areole %s"
              % (len(scenes), results.get("areole_version")))
        return 0

    if problems:
        print("Refusing to write a document from an incomplete baseline.")
        return 1

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s from %d scenes" % (OUT, len(scenes)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
