#!/usr/bin/env python
"""Generate src/ar_color_tables.h and src/ar_color_names.h.

Three tables that a C89 file cannot compute for itself and that nobody should
type by hand:

  AR_SRGB_LIN   the sRGB transfer function, decode direction. It needs a 2.4
                power, and there is no pow() in areole -- the whole point of
                the table is that the runtime never needs one.
  AR_SIN_DEG    sine per whole degree. Same argument.
  AR_NAMED      the 148 CSS named colours, sorted so the lookup can bisect.

Run after changing AR_CFIX in ar_color.h, and never edit the output.
"""

import math
import os

F = 4096
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

NAMED = """aliceblue F0F8FF antiquewhite FAEBD7 aqua 00FFFF aquamarine 7FFFD4 azure F0FFFF
beige F5F5DC bisque FFE4C4 black 000000 blanchedalmond FFEBCD blue 0000FF blueviolet 8A2BE2
brown A52A2A burlywood DEB887 cadetblue 5F9EA0 chartreuse 7FFF00 chocolate D2691E coral FF7F50
cornflowerblue 6495ED cornsilk FFF8DC crimson DC143C cyan 00FFFF darkblue 00008B darkcyan 008B8B
darkgoldenrod B8860B darkgray A9A9A9 darkgreen 006400 darkgrey A9A9A9 darkkhaki BDB76B
darkmagenta 8B008B darkolivegreen 556B2F darkorange FF8C00 darkorchid 9932CC darkred 8B0000
darksalmon E9967A darkseagreen 8FBC8F darkslateblue 483D8B darkslategray 2F4F4F darkslategrey 2F4F4F
darkturquoise 00CED1 darkviolet 9400D3 deeppink FF1493 deepskyblue 00BFFF dimgray 696969
dimgrey 696969 dodgerblue 1E90FF firebrick B22222 floralwhite FFFAF0 forestgreen 228B22
fuchsia FF00FF gainsboro DCDCDC ghostwhite F8F8FF gold FFD700 goldenrod DAA520 gray 808080
green 008000 greenyellow ADFF2F grey 808080 honeydew F0FFF0 hotpink FF69B4 indianred CD5C5C
indigo 4B0082 ivory FFFFF0 khaki F0E68C lavender E6E6FA lavenderblush FFF0F5 lawngreen 7CFC00
lemonchiffon FFFACD lightblue ADD8E6 lightcoral F08080 lightcyan E0FFFF lightgoldenrodyellow FAFAD2
lightgray D3D3D3 lightgreen 90EE90 lightgrey D3D3D3 lightpink FFB6C1 lightsalmon FFA07A
lightseagreen 20B2AA lightskyblue 87CEFA lightslategray 778899 lightslategrey 778899
lightsteelblue B0C4DE lightyellow FFFFE0 lime 00FF00 limegreen 32CD32 linen FAF0E6 magenta FF00FF
maroon 800000 mediumaquamarine 66CDAA mediumblue 0000CD mediumorchid BA55D3 mediumpurple 9370DB
mediumseagreen 3CB371 mediumslateblue 7B68EE mediumspringgreen 00FA9A mediumturquoise 48D1CC
mediumvioletred C71585 midnightblue 191970 mintcream F5FFFA mistyrose FFE4E1 moccasin FFE4B5
navajowhite FFDEAD navy 000080 oldlace FDF5E6 olive 808000 olivedrab 6B8E23 orange FFA500
orangered FF4500 orchid DA70D6 palegoldenrod EEE8AA palegreen 98FB98 paleturquoise AFEEEE
palevioletred DB7093 papayawhip FFEFD5 peachpuff FFDAB9 peru CD853F pink FFC0CB plum DDA0DD
powderblue B0E0E6 purple 800080 rebeccapurple 663399 red FF0000 rosybrown BC8F8F royalblue 4169E1
saddlebrown 8B4513 salmon FA8072 sandybrown F4A460 seagreen 2E8B57 seashell FFF5EE sienna A0522D
silver C0C0C0 skyblue 87CEEB slateblue 6A5ACD slategray 708090 slategrey 708090 snow FFFAFA
springgreen 00FF7F steelblue 4682B4 tan D2B48C teal 008080 thistle D8BFD8 tomato FF6347
turquoise 40E0D0 violet EE82EE wheat F5DEB3 white FFFFFF whitesmoke F5F5F5 yellow FFFF00
yellowgreen 9ACD32"""

BANNER = "/* Generated by tools/gen_color_tables.py -- do not edit by hand. */"


def srgb_to_linear(c8):
    c = c8 / 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def rows(vals, per, width):
    out = []
    for i in range(0, len(vals), per):
        out.append("    " + ", ".join(("%" + str(width) + "d") % v for v in vals[i:i + per]) + ",")
    return "\n".join(out)


def write_tables(path):
    lin = [min(F, int(round(srgb_to_linear(i) * F))) for i in range(256)]
    sin = [int(round(math.sin(math.radians(d)) * F)) for d in range(91)]

    with open(path, "w", newline="\n") as f:
        f.write(BANNER + "\n#ifndef AR_COLOR_TABLES_H\n#define AR_COLOR_TABLES_H\n\n")
        f.write("/* sRGB transfer, decode direction, in AR_CFIX scale. 256 entries of two\n")
        f.write("   bytes. Encoding bisects this same table, so the two directions cannot\n")
        f.write("   drift apart the way two independent approximations would. */\n")
        f.write("static const ar_u16 AR_SRGB_LIN[256] = {\n%s\n};\n\n" % rows(lin, 8, 4))
        f.write("/* sin, one entry per whole degree from 0 to 90, in AR_CFIX scale.\n")
        f.write("   Linear interpolation between entries is good to about 0.16 of one\n")
        f.write("   fixed-point unit, far inside the 1/255 a channel is read to. */\n")
        f.write("static const ar_u16 AR_SIN_DEG[91] = {\n%s\n};\n\n" % rows(sin, 8, 4))
        f.write("#endif\n")


def write_names(path):
    words = NAMED.split()
    pairs = sorted(zip(words[0::2], words[1::2]))
    if len(pairs) != len(set(n for n, _ in pairs)):
        raise SystemExit("duplicate colour name in the source list")

    with open(path, "w", newline="\n") as f:
        f.write(BANNER + "\n#ifndef AR_COLOR_NAMES_H\n#define AR_COLOR_NAMES_H\n\n")
        f.write("/* The %d CSS named colours, sorted so the lookup can bisect.\n" % len(pairs))
        f.write("   ar_test asserts the ordering rather than trusting this comment. */\n")
        f.write("static const ar__named AR_NAMED[] = {\n")
        for n, h in pairs:
            f.write('    {"%s", 0x%sul},\n' % (n, h))
        f.write("};\n\n")
        f.write("#define AR_NAMED_COUNT ((ar_u32)(sizeof(AR_NAMED) / sizeof(AR_NAMED[0])))\n\n")
        f.write("#endif\n")
    return len(pairs)


def main():
    src = os.path.join(ROOT, "src")
    write_tables(os.path.join(src, "ar_color_tables.h"))
    n = write_names(os.path.join(src, "ar_color_names.h"))
    print("wrote ar_color_tables.h (256 + 91 entries) and ar_color_names.h (%d colours)" % n)


if __name__ == "__main__":
    main()
