#!/usr/bin/env python3
"""Generate the `@supports` corpus from the implementation's own property table.

    python tools/gen_supports_corpus.py            # write the header
    python tools/gen_supports_corpus.py --check    # and fail if it is stale

Writes `tests/ar_supports_props.h`: every property name in `AR_PROPS`, which is
the table `ar__parse_decl` looks a declaration up in.

------------------------------------------------------------------------
Why generated

Because a hand-written list is a second record of one fact, and the two drift.
0.4.2's acceptance criterion says the corpus covers every property in the
catalogue and says *generated* in the same sentence, for exactly that reason:
a property added to the parser and forgotten in the corpus is a property
`@supports` could start lying about with nothing to notice.

The test this feeds does not ask "is this name in a list of supported names".
It asks whether `@supports (name: value)` and a rule that actually writes
`name: value` agree about whether anything happened. Those are different code
paths -- the first runs `ar__parse_decl` on a scanner bounded by the closing
bracket and puts the sheet's bookkeeping back, the second parses a real
declaration block -- and the whole value of `@supports` rests on them never
disagreeing.

A development tool, like `gen_font.py` and `gen_entities.py`: the output is
committed and no build needs Python.
"""

import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'src', 'ar_css.c')
OUT = os.path.join(ROOT, 'tests', 'ar_supports_props.h')

BANNER = '/* GENERATED by tools/gen_supports_corpus.py. Do not edit. */\n'


def properties():
    """-> [name], every entry of AR_PROPS, in source order."""
    with io.open(SRC, encoding='utf-8') as f:
        text = f.read()
    names = re.findall(r'\{"([a-z-]+)",\s*AR_P_[A-Z_0-9]+\}', text)
    # A name may appear twice if two spellings map to one property; keep the
    # first of each, because the corpus asks about names and not about slots.
    seen, out = set(), []
    for n in names:
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def render(names):
    w = [BANNER,
         '/*\n'
         ' * Every property name the declaration parser knows, so the @supports\n'
         ' * corpus cannot fall behind the parser it is meant to be checking.\n'
         ' *\n'
         ' * Regenerate with tools/gen_supports_corpus.py.\n'
         ' */\n',
         'static const char *const AR_SUPPORTS_PROPS[] = {\n']
    for n in names:
        w.append('    "%s",\n' % n)
    w.append('};\n\n')
    w.append('#define AR_SUPPORTS_PROP_N '
             '((ar_i32)(sizeof AR_SUPPORTS_PROPS / sizeof AR_SUPPORTS_PROPS[0]))\n')
    return ''.join(w)


def main():
    names = properties()
    if not names:
        print('found no properties in %s -- has AR_PROPS moved?' % SRC)
        return 2
    text = render(names)

    if '--check' in sys.argv:
        if not os.path.exists(OUT):
            print('FAIL: %s does not exist' % os.path.relpath(OUT, ROOT))
            return 1
        with io.open(OUT, encoding='utf-8') as f:
            if f.read() != text:
                print('FAIL: %s is stale -- run tools/gen_supports_corpus.py'
                      % os.path.relpath(OUT, ROOT))
                return 1
        print('the @supports corpus covers all %d properties' % len(names))
        return 0

    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('wrote %s, %d properties' % (os.path.relpath(OUT, ROOT), len(names)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
